#!/bin/bash

set -e

if (($(id -u) != 0)); then
  printf 'root is required, try: sudo %s\n' "$0"
  exit 1
fi

apt-get update -y
apt-get upgrade -y
apt-get install --no-install-recommends -y \
  ca-certificates \
  build-essential \
  automake \
  pkg-config \
  yacc \
  bash \
  zsh \
  procps \
  git \
  curl \
  unzip \
  bc \
  python3 \
  python3-pip \
  tmux
