#!/bin/bash

set -e

if (($(id -u) != 0)); then
  printf 'root is required, try: sudo %s\n' "$0"
  exit 1
fi

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$repo_dir"/provision/base

# install packages
apt-get install --no-install-recommends -y \
  podman \
  cmake \
  meson \
  util-linux \
  libncurses-dev \
  libevent-dev

# wsl-vhd
if [[ ! -f /usr/local/bin/wsl-vhd ]]; then
  apt-get install --no-install-recommends -y \
    qemu-utils \
    btrfs-progs \
    ntfs-3g \
    exfat-fuse \
    exfatprogs \
    dosfstools

  curl -Ls 'https://raw.githubusercontent.com/kmmiles/wsl-vhd-bash/main/wsl-vhd' > /usr/local/bin/wsl-vhd
  chmod +x /usr/local/bin/wsl-vhd
fi
