#!/bin/bash

set -e

if (($(id -u) != 0)); then
  printf 'root is required, try: sudo %s\n' "$0"
  exit 1
fi

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$repo_dir"/provision/base

dnf config-manager --set-enabled crb
dnf install -y epel-release
dnf install -y \
  podman \
  podman-compose \
  kernel-devel \
  cmake \
  meson \
  wayland-devel \
  wayland-protocols-devel

# checkout and install wl-clipboard
PATH="$PATH:/usr/local/bin"
if ! command -v "wl-copy" > /dev/null; then
  repo="/tmp/wl-clipboard"
  if [[ ! -d "$repo" ]]; then
    git clone https://github.com/bugaevc/wl-clipboard.git "$repo"
  fi
  cd "$repo" && meson build && cd build && ninja && ninja install
fi
