FROM fedora

RUN set -ex; \
  dnf install -y \
    ca-certificates \
    bash \
    procps \
    git \
    curl \
    unzip

COPY . /app
WORKDIR /app

RUN set -ex; \
  curl -sS https://raw.githubusercontent.com/kmmiles/dotfiles/main/netinstall | bash
