FROM ubuntu

RUN set -ex; \
  apt-get update && \
  apt-get -y install --no-install-recommends \
    ca-certificates \
    bash \
    git \
    curl \
    unzip

RUN set -ex; \
  curl -sS https://raw.githubusercontent.com/kmmiles/dotfiles/main/install | bash
