#!/bin/bash

set -euo pipefail

for dep in bash git curl unzip; do
  if ! command -v "$dep" > /dev/null 2>&1; then
    printf 'Command not found: %s\n' "$dep"
    exit 1
  fi
done

checkout_base_dir="$HOME/.local/src"
mkdir -p "$checkout_base_dir"
cd "$checkout_base_dir" || exit 1

if [[ -d "./dotfiles" ]]; then
  cd "./dotfiles" || exit 1
  git pull
else
  git clone "https://github.com/kmmiles/dotfiles"
  cd "./dotfiles" || exit 1
fi

./install "$@"
