# every url used in `install`
declare -A urls
urls[dotfiles]="https://github.com/kmmiles/dotfiles.git"
urls[zsh-syntax-highlighting]="https://github.com/zsh-users/zsh-syntax-highlighting"
urls[zsh-autosuggestions]="https://github.com/zsh-users/zsh-autosuggestions"
urls[zsh-history-substring-search]="https://github.com/zsh-users/zsh-history-substring-search"
urls[zsh-completions]="https://github.com/zsh-users/zsh-completions"
urls[nord-dircolors]="https://github.com/arcticicestudio/nord-dircolors"
urls[nord-tmux]="https://github.com/arcticicestudio/nord-tmux"
urls[nord-vim]="https://github.com/arcticicestudio/nord-vim"
urls[odin]="https://github.com/Tetralux/odin.vim"
urls[ale]="https://github.com/dense-analysis/ale.git"
urls[vim-go]="https://github.com/fatih/vim-go.git"
urls[tpm]="https://github.com/tmux-plugins/tpm"
urls[youtube-dl]="https://yt-dl.org/downloads/latest/youtube-dl"
urls[prettyping]="https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping"
